# Example usage

```{r, eval = TRUE, comment = "#>", collapse = TRUE}
library(tjm.praat)
library(magrittr, warn.conflicts = FALSE)

# Use the PATH to find praat
praat_path <- Sys.which("praat")

tg <- system.file(
  "demo-textgrids/merge-duplicate-intervals.TextGrid",
  package = "tjm.praat"
)

tg_out <- tempfile("test", fileext = ".TextGrid")

# Note that there are three tiers
tg %>% 
  readtextgrid::read_textgrid() %>% 
  magrittr::extract(c("tier_num", "tier_name")) %>% 
  unique()

f_duplicate_tier <- wrap_praat_script(
  praat_location = praat_path,
  script_code_to_run = duplicate_tier,
  return = "last-argument"
)

tg_out <- tg %>% 
  f_duplicate_tier("phones", "duplicate-is-first", "first", tg_out) %>% 
  f_duplicate_tier("phones", "duplicate-is-last", "last", tg_out) %>% 
  f_duplicate_tier("phones", "duplicate-is-after", "after", tg_out) %>% 
  f_duplicate_tier("phones", "duplicate-is-before", "before", tg_out)

# We duplicated "phones" four times and 
# placed the copy into separate locations
tg_out %>% 
  readtextgrid::read_textgrid() %>% 
  magrittr::extract(c("tier_num", "tier_name")) %>% 
  unique()
```

# Praat source code

```{r, echo = FALSE, comment = ""}
duplicate_tier
```

